language: node_js
node_js:
  - lts/*
cache:
  directories:
    - node_modules #缓存依赖
install:
  - npm ci
script:
  - npm run docs:build
  - cd docs/.vuepress/dist
  - echo 'www.easyrentsh.xyz' > CNAME
  - git config --global user.email "1562055324@qq.com"
  - git config --global user.name "harryzq"
  - git init
  - git add .
  - git commit -m 'deploy'
  - git push -f "https://${GH_TOKEN}@github.com/harryzq/harryzq.github.io.git" master
branches:
  only:
  - dev
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: $GH_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  on:
    branch: dev